# Generated by Django 4.2.7 on 2023-12-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=32)),
                ("email", models.CharField(max_length=32)),
            ],
        ),
    ]
