# Generated by Django 4.2.7 on 2023-12-09 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0005_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReComment",
        ),
    ]
