# Generated by Django 4.2.7 on 2023-12-09 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0006_delete_recomment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="History",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Information",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
