# Generated by Django 4.2.7 on 2023-12-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app01", "0007_delete_comment_delete_history_delete_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nid", models.CharField(max_length=32)),
                ("username", models.CharField(max_length=32)),
                ("time", models.CharField(max_length=32)),
                ("com", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hid", models.IntegerField(max_length=32)),
                ("username", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="static/form")),
            ],
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("realname", models.CharField(max_length=32)),
                ("qianming", models.CharField(max_length=32)),
                ("tel", models.CharField(max_length=32)),
                ("age", models.CharField(max_length=32)),
                ("gender", models.CharField(max_length=32)),
                ("text", models.TextField()),
                ("location", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ReComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nid", models.IntegerField(max_length=32)),
                ("username", models.CharField(max_length=32)),
                ("time", models.CharField(max_length=32)),
                ("com", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=32)),
                ("email", models.CharField(max_length=32)),
            ],
        ),
    ]
